//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_SignedUpToEvent
    {
        public int eventId { get; set; }
        public int availablePlaces { get; set; }
        public string UserEmail { get; set; }
        public string SignedUpUserEmail { get; set; }
        public byte[] rowVersion { get; set; }
    
        public virtual RV_AppUser RV_AppUser { get; set; }
        public virtual RV_AppUser RV_AppUser1 { get; set; }
        public virtual RV_Event RV_Event { get; set; }
    }
}
