//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RV_User()
        {
            this.RV_Group = new HashSet<RV_Group>();
            this.RV_Message = new HashSet<RV_Message>();
            this.RV_NoteFromSystemManager = new HashSet<RV_NoteFromSystemManager>();
            this.RV_ChatRoom = new HashSet<RV_ChatRoom>();
            this.RV_Group1 = new HashSet<RV_Group>();
        }
    
        public string email { get; set; }
        public string code { get; set; }
        public Nullable<int> typeId { get; set; }
    
        public virtual RV_AppUser RV_AppUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_Group> RV_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_Message> RV_Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_NoteFromSystemManager> RV_NoteFromSystemManager { get; set; }
        public virtual RV_UserType RV_UserType { get; set; }
        public virtual RV_WineryManager RV_WineryManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_ChatRoom> RV_ChatRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV_Group> RV_Group1 { get; set; }
    }
}
