//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_Comment
    {
        public int commentId { get; set; }
        public Nullable<System.DateTime> commentDate { get; set; }
        public Nullable<System.DateTime> commentTime { get; set; }
        public string content { get; set; }
        public int wineId { get; set; }
        public string respondedUserEmail { get; set; }
    
        public virtual RV_Wine RV_Wine { get; set; }
    }
}
