//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_Winery
    {
        public int wineryId { get; set; }
        public string wineryName { get; set; }
        public string wineryAddress { get; set; }
        public string wineryEmail { get; set; }
        public string phone { get; set; }
        public string statusType { get; set; }
        public string IconImgPath { get; set; }
        public Nullable<int> areaId { get; set; }
        public string wineryManagerEmail { get; set; }
    
        public virtual RV_User RV_User { get; set; }
    }
}
